/**
 * Script to test the blog publishing API
 * Sends a simple test request to verify the API is working
 */

interface ApiResponse {
  status: string;
  configured: boolean;
  message: string;
  requiredEnvVars: string[];
}

interface TestBlogPost {
  title: string;
  description: string;
  author: string;
  date: string;
  published: boolean;
  content: string;
}

function getApiUrl(): string {
  if (process.env.API_URL) {
    return process.env.API_URL;
  }
  
  if (process.env.VERCEL_URL) {
    return `https://${process.env.VERCEL_URL}/api/publish-blog`;
  }
  
  return 'http://localhost:3000/api/publish-blog';
}

async function testApiStatus(): Promise<boolean> {
  const apiUrl = getApiUrl();
  console.log(`🔍 Testing API status at: ${apiUrl}`);
  
  try {
    const response = await fetch(apiUrl, {
      method: 'GET',
    });
    
    if (response.ok) {
      const result: ApiResponse = await response.json();
      console.log('✅ API Status:', result.status);
      console.log('🔧 Configured:', result.configured);
      console.log('📝 Message:', result.message);
      
      if (!result.configured) {
        console.log('⚠️  Required environment variables:', result.requiredEnvVars.join(', '));
        return false;
      }
      
      return true;
    } else {
      console.error('❌ API status check failed:', response.status);
      return false;
    }
  } catch (error) {
    console.error('❌ Error testing API:', error);
    return false;
  }
}

async function testApiWithSampleBlog(): Promise<boolean> {
  const apiUrl = getApiUrl();
  console.log(`🧪 Testing API with sample blog post...`);
  
  const testBlog: TestBlogPost = {
    title: 'API Test Blog Post',
    description: 'This is a test blog post to verify the API is working correctly.',
    author: 'API Tester',
    date: new Date().toISOString().split('T')[0],
    published: true,
    content: `# API Test Blog Post

This is a test blog post generated by the API testing script.

## Purpose

This post is used to verify that:
- The API endpoint is accessible
- Authentication is working
- Blog post creation is functional
- GitHub integration is operational

## Test Details

- **Generated**: ${new Date().toISOString()}
- **Test Type**: API Integration Test
- **Expected Result**: Successful blog post creation

## Conclusion

If you can see this post, the API is working correctly! 🎉`
  };

  try {
    const response = await fetch(apiUrl, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({
        blogs: [testBlog],
        mode: 'batch',
        batchTitle: 'API Test - Single Blog Post',
        options: {
          labels: ['api-test', 'automated'],
          autoMerge: false
        }
      }),
    });

    const result = await response.json();

    if (response.ok && result.success) {
      console.log('✅ API test successful!');
      console.log('📋 Summary:', result.summary);
      
      if (result.result) {
        console.log('🔗 Pull Request:', result.result.pullRequestUrl);
        console.log('📝 PR Title:', result.result.title);
      }
      
      return true;
    } else {
      console.error('❌ API test failed');
      console.error('Error:', result.error || 'Unknown error');
      console.error('Response status:', response.status);
      return false;
    }
  } catch (error) {
    console.error('❌ Error testing API with sample blog:', error);
    return false;
  }
}

async function runApiTests(): Promise<void> {
  console.log('🚀 Starting API tests...\n');
  
  // Test 1: API Status
  console.log('1️⃣ Testing API status...');
  const statusOk = await testApiStatus();
  
  if (!statusOk) {
    console.log('\n❌ API status test failed. Please check your configuration.');
    process.exit(1);
  }
  
  console.log('\n2️⃣ Testing API with sample blog post...');
  const blogTestOk = await testApiWithSampleBlog();
  
  if (blogTestOk) {
    console.log('\n🎉 All API tests passed! The API is ready for use.');
  } else {
    console.log('\n❌ API blog test failed. Please check your GitHub configuration.');
    process.exit(1);
  }
}

// Main execution
if (require.main === module) {
  runApiTests()
    .then(() => {
      console.log('\n✅ API testing completed successfully!');
    })
    .catch((error) => {
      console.error('\n💥 API testing failed:', error);
      process.exit(1);
    });
}

export { testApiStatus, testApiWithSampleBlog, runApiTests };
